# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 545e9e25cc8c122231f8d0af6c709e3c2a3420c18542479e30f1e1884dda4bdbf4e9081dd41b134fdc09f2a7bef728961a4a4d2330c8dedec4a775a288c4707f

test:
  secret_key_base: dcc130f75098fa4b84afddbba1b6a82551c215dedd4e7d4819f9034477a51b0a09aea3f1593f3a8db2dd4717fbe79477233ad14fccbdff737cba157a80449ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
